/about             /about/index.html  200
/explore           /explore/index.html 200
/life              /life/index.html  200
/contact           /contact/index.html  200
/events            /events/index.html  200
/*                 /index.html       200